#ifndef _GRAPHICS_TYPES_H
#define _GRAPHICS_TYPES_H

enum draw_mode {
	DRAW_MODE_POINTS,
	DRAW_MODE_LINE_STRIP,
	DRAW_MODE_LINE_LOOP,
	DRAW_MODE_LINES,
	DRAW_MODE_LINE_STRIP_ADJACENCY,
	DRAW_MODE_LINES_ADJACENCY,
	DRAW_MODE_TRIANGLE_STRIP,
	DRAW_MODE_TRIANGLE_FAN,
	DRAW_MODE_TRIANGLES,
	DRAW_MODE_TRIANGLE_STRIP_ADJACENCY,
	DRAW_MODE_TRIANGLES_ADJACENCY,
	DRAW_MODE_PATCHES
};

#endif